/**
 * 開発用シードデータ（トランザクション系: serviceItems/records/serviceOrders）。
 * today からの相対日付で構成するため、today を引数に取る関数として提供する
 * （src/dev/seed.ts から呼び出される）。
 */

import { DEFAULT_BUFFER_DAYS, DEFAULT_NOTICE_DAYS_BEFORE } from "@/domain/constants";
import {
  type ServiceOrder,
  CYCLE,
  EXECUTION,
  type ServiceItem,
  type ServiceRecord,
  type IsoDateString,
  SERVICE_ITEM_TYPE,
  SERVICE_ORDER_STATUS,
  RECORD_RESULT,
} from "@/store/types";
import { addDays } from "@/utils/time";

export const buildSeedServiceItems = (today: IsoDateString): Record<string, ServiceItem> => ({
  "seed-item-overdue": {
    id: "seed-item-overdue",
    equipmentId: "seed-equipment-001",
    type: SERVICE_ITEM_TYPE.INSPECTION,
    execution: EXECUTION.INTERNAL,
    name: "絶縁抵抗点検",
    cycle: CYCLE.Y1,
    personId: "seed-person-sato",
    bufferDays: DEFAULT_BUFFER_DAYS,
    noticeDaysBefore: DEFAULT_NOTICE_DAYS_BEFORE,
    nextDueDate: addDays(today, -10) ?? today,
    lastDoneDate: addDays(today, -375) ?? today,
    isActive: true,
  },
  "seed-item-order-now": {
    id: "seed-item-order-now",
    equipmentId: "seed-equipment-002",
    type: SERVICE_ITEM_TYPE.CALIBRATION,
    execution: EXECUTION.EXTERNAL,
    name: "トルク校正",
    cycle: CYCLE.Y1,
    vendorId: "seed-vendor-tokyo",
    personId: "seed-person-suzuki",
    bufferDays: DEFAULT_BUFFER_DAYS,
    noticeDaysBefore: DEFAULT_NOTICE_DAYS_BEFORE,
    nextDueDate: addDays(today, 20) ?? today,
    // なぜ -345 か: 周期1Yの自動計算(lastDone + 365日)と nextDueDate(today+20)が
    // おおむね一致するようにし、画面上の前回実施日と次回期限の整合を保つため。
    lastDoneDate: addDays(today, -345) ?? today,
    isActive: true,
  },
  "seed-item-in-progress": {
    id: "seed-item-in-progress",
    equipmentId: "seed-equipment-003",
    type: SERVICE_ITEM_TYPE.CALIBRATION,
    execution: EXECUTION.EXTERNAL,
    name: "寸法校正",
    cycle: CYCLE.Y1,
    vendorId: "seed-vendor-osaka",
    personId: "seed-person-takahashi",
    bufferDays: DEFAULT_BUFFER_DAYS,
    noticeDaysBefore: DEFAULT_NOTICE_DAYS_BEFORE,
    nextDueDate: addDays(today, 25) ?? today,
    isActive: true,
  },
  "seed-item-due-soon": {
    id: "seed-item-due-soon",
    equipmentId: "seed-equipment-001",
    type: SERVICE_ITEM_TYPE.INSPECTION,
    execution: EXECUTION.INTERNAL,
    name: "動作点検",
    cycle: CYCLE.M6,
    personId: "seed-person-sato",
    bufferDays: DEFAULT_BUFFER_DAYS,
    noticeDaysBefore: DEFAULT_NOTICE_DAYS_BEFORE,
    nextDueDate: addDays(today, 7) ?? today,
    lastDoneDate: addDays(today, -173) ?? today,
    isActive: true,
  },
  "seed-item-ok": {
    id: "seed-item-ok",
    equipmentId: "seed-equipment-004",
    type: SERVICE_ITEM_TYPE.INSPECTION,
    execution: EXECUTION.INTERNAL,
    name: "定期点検",
    cycle: CYCLE.Y1,
    personId: "seed-person-suzuki",
    bufferDays: DEFAULT_BUFFER_DAYS,
    noticeDaysBefore: DEFAULT_NOTICE_DAYS_BEFORE,
    nextDueDate: addDays(today, 180) ?? today,
    lastDoneDate: addDays(today, -185) ?? today,
    isActive: true,
  },
  "seed-item-ok-external": {
    id: "seed-item-ok-external",
    equipmentId: "seed-equipment-004",
    type: SERVICE_ITEM_TYPE.CALIBRATION,
    execution: EXECUTION.EXTERNAL,
    name: "圧力校正",
    cycle: CYCLE.Y1,
    vendorId: "seed-vendor-both",
    leadTimeDays: 10,
    personId: "seed-person-takahashi",
    bufferDays: DEFAULT_BUFFER_DAYS,
    noticeDaysBefore: DEFAULT_NOTICE_DAYS_BEFORE,
    nextDueDate: addDays(today, 120) ?? today,
    isActive: true,
  },
  // なぜ追加するか: 一覧の表示対象（稼働機器×有効項目）で 種別×実施区分 の4組合せ
  // （点検×内部/点検×外部/校正×内部/校正×外部）を網羅し、フィルタ確認で0件にならないようにする。
  "seed-item-external-inspection": {
    id: "seed-item-external-inspection",
    equipmentId: "seed-equipment-002",
    type: SERVICE_ITEM_TYPE.INSPECTION,
    execution: EXECUTION.EXTERNAL,
    name: "精度点検",
    cycle: CYCLE.Y1,
    vendorId: "seed-vendor-tokyo",
    personId: "seed-person-suzuki",
    bufferDays: DEFAULT_BUFFER_DAYS,
    noticeDaysBefore: DEFAULT_NOTICE_DAYS_BEFORE,
    nextDueDate: addDays(today, 150) ?? today,
    lastDoneDate: addDays(today, -215) ?? today,
    isActive: true,
  },
  "seed-item-internal-calibration": {
    id: "seed-item-internal-calibration",
    equipmentId: "seed-equipment-003",
    type: SERVICE_ITEM_TYPE.CALIBRATION,
    execution: EXECUTION.INTERNAL,
    name: "基準器校正",
    cycle: CYCLE.M6,
    personId: "seed-person-sato",
    bufferDays: DEFAULT_BUFFER_DAYS,
    noticeDaysBefore: DEFAULT_NOTICE_DAYS_BEFORE,
    nextDueDate: addDays(today, 15) ?? today,
    lastDoneDate: addDays(today, -168) ?? today,
    isActive: true,
  },
  "seed-item-inactive": {
    id: "seed-item-inactive",
    equipmentId: "seed-equipment-002",
    type: SERVICE_ITEM_TYPE.INSPECTION,
    execution: EXECUTION.INTERNAL,
    name: "旧点検項目",
    cycle: CYCLE.M6,
    personId: "seed-person-sato",
    bufferDays: DEFAULT_BUFFER_DAYS,
    noticeDaysBefore: DEFAULT_NOTICE_DAYS_BEFORE,
    nextDueDate: addDays(today, 50) ?? today,
    isActive: false,
  },
  "seed-item-suspended-eq": {
    id: "seed-item-suspended-eq",
    equipmentId: "seed-equipment-005",
    type: SERVICE_ITEM_TYPE.CALIBRATION,
    execution: EXECUTION.EXTERNAL,
    name: "秤量校正",
    cycle: CYCLE.Y1,
    vendorId: "seed-vendor-tokyo",
    personId: "seed-person-takahashi",
    bufferDays: DEFAULT_BUFFER_DAYS,
    noticeDaysBefore: DEFAULT_NOTICE_DAYS_BEFORE,
    nextDueDate: addDays(today, 60) ?? today,
    isActive: true,
  },
});

export const buildSeedRecords = (today: IsoDateString): Record<string, ServiceRecord> => ({
  "seed-record-overdue-pass": {
    id: "seed-record-overdue-pass",
    serviceItemId: "seed-item-overdue",
    doneDate: addDays(today, -375) ?? today,
    doneBy: "佐藤 由紀子",
    result: RECORD_RESULT.PASS,
    note: "定期点検実施",
  },
  "seed-record-overdue-fail": {
    id: "seed-record-overdue-fail",
    serviceItemId: "seed-item-overdue",
    doneDate: addDays(today, -740) ?? today,
    doneBy: "佐藤 由紀子",
    result: RECORD_RESULT.FAIL,
    note: "基準値超過のため再点検",
  },
  "seed-record-due-soon": {
    id: "seed-record-due-soon",
    serviceItemId: "seed-item-due-soon",
    doneDate: addDays(today, -173) ?? today,
    doneBy: "佐藤 由紀子",
    result: RECORD_RESULT.PASS,
  },
  "seed-record-ok": {
    id: "seed-record-ok",
    serviceItemId: "seed-item-ok",
    doneDate: addDays(today, -185) ?? today,
    doneBy: "鈴木 健太",
    result: RECORD_RESULT.ADJUSTED,
    note: "経年劣化により調整",
  },
  "seed-record-external-inspection": {
    id: "seed-record-external-inspection",
    serviceItemId: "seed-item-external-inspection",
    doneDate: addDays(today, -215) ?? today,
    doneBy: "東京計測サービス",
    result: RECORD_RESULT.PASS,
  },
  "seed-record-internal-calibration": {
    id: "seed-record-internal-calibration",
    serviceItemId: "seed-item-internal-calibration",
    doneDate: addDays(today, -168) ?? today,
    doneBy: "佐藤 由紀子",
    result: RECORD_RESULT.PASS,
  },
  "seed-record-order-now-completed": {
    id: "seed-record-order-now-completed",
    serviceItemId: "seed-item-order-now",
    doneDate: addDays(today, -345) ?? today,
    doneBy: "東京計測サービス",
    result: RECORD_RESULT.PASS,
    serviceOrderId: "seed-order-completed",
  },
});

export const buildSeedServiceOrders = (today: IsoDateString): Record<string, ServiceOrder> => ({
  "seed-order-in-calib": {
    id: "seed-order-in-calib",
    serviceItemId: "seed-item-in-progress",
    vendorId: "seed-vendor-osaka",
    status: SERVICE_ORDER_STATUS.IN_CALIBRATION,
    orderedDate: addDays(today, -5) ?? today,
    dueDate: addDays(today, 14) ?? today,
  },
  "seed-order-planned": {
    id: "seed-order-planned",
    serviceItemId: "seed-item-ok-external",
    vendorId: "seed-vendor-both",
    status: SERVICE_ORDER_STATUS.PLANNED,
  },
  "seed-order-returned": {
    id: "seed-order-returned",
    serviceItemId: "seed-item-suspended-eq",
    vendorId: "seed-vendor-tokyo",
    status: SERVICE_ORDER_STATUS.RETURNED,
    orderedDate: addDays(today, -20) ?? today,
    dueDate: addDays(today, -5) ?? today,
    returnedDate: addDays(today, -2) ?? today,
  },
  "seed-order-completed": {
    id: "seed-order-completed",
    serviceItemId: "seed-item-order-now",
    vendorId: "seed-vendor-tokyo",
    status: SERVICE_ORDER_STATUS.COMPLETED,
    orderedDate: addDays(today, -380) ?? today,
    dueDate: addDays(today, -359) ?? today,
    returnedDate: addDays(today, -350) ?? today,
    cost: 18_000,
  },
  "seed-order-cancelled": {
    id: "seed-order-cancelled",
    serviceItemId: "seed-item-in-progress",
    vendorId: "seed-vendor-osaka",
    status: SERVICE_ORDER_STATUS.CANCELLED,
    orderedDate: addDays(today, -40) ?? today,
    note: "納期調整のためキャンセルし再発注",
  },
});
